
###
# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

#test chance of rain - pick up city seeing: "chance of precipitation" at https://www.weather.gov/forecastmaps

GET http://127.0.0.1:8000/api/umbrella?city=portland
Accept: application/json

###

GET http://localhost:8000/api/umbrella?city=san+diego
Accept: application/json

###

GET http://localhost:8000/api/umbrella?city=san+francisco
Accept: application/json

###

GET http://localhost:8000/api/umbrella?city=Vancouver&country=ca
Accept: application/json

###

GET http://localhost:8000/api/umbrella?city=Chicago
Accept: application/json

###

GET http://localhost:8000/api/umbrella?city=Peoria
Accept: application/json